#
# 
#
version: '3.8'

services:

    webserver:
      image: httpd:2.4
      container_name: a301_2020_web
      ports:
        - "${TEXT_PORT}:80"
      volumes:
        - ./notebooks:/srv/notebooks
        - "/var/run/docker.sock:/var/run/docker.sock"
      command: bash -c
              "cp -a /srv/notebooks/_build/html/* /usr/local/apache2/htdocs/.
               && httpd-foreground
              "


