#
# 
#
version: '3.8'

services:

#
# copy notebooks and html files in ./notebooks on host
# to /srv/problem_solving_content and create
# a named volume holding that target
#
  content:
    container_name: a301_content
    build:
      context: .
      dockerfile: content.dockerfile
    image: phaustin/a301_content:sep09
    volumes:
      - type: volume
        source: a301-notebooks
        target: /srv/a301_notebooks
#
# start a web server at port .env:TEXT_PORT
# with the html files from book_content
#
  webserver:
    build:
      context: apache_webserver
      dockerfile: Dockerfile
    image: phaustin/a301_server:sep09
    depends_on: [content]
    container_name: a301_webserver
    ports:
      - "${TEXT_PORT}:80"
    volumes:
      - a301-notebooks:/srv/notebooks
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: bash -c
            "cp -a /srv/notebooks/_build/html/* /usr/local/apache2/htdocs/.
             && httpd-foreground
            "


    networks:
      - jupyterhub

                 
# explicitly name the network rather than letting docker_compose assign
networks:
    jupyterhub:
      driver: bridge
      name: jupyterhub

volumes:
  a301-notebooks:
    name: a301-notebooks

